version: '3.3'
services:
  redis:
    restart: always
    image: sameersbn/redis
    container_name: gitlab-redis
    volumes:
      - /application/services/redis:/var/lib/redis:Z
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    container_name: gitlab-postgresql
    ports:
      - "5432:5432"
    volumes:
      - /application/services/postgresql/data:/var/lib/postgresql:Z
    environment:
      - DB_USER=gitlab
      - DB_PASS=gitlab
      - DB_NAME=gitlabhq_production
      - DB_EXTENSION=pg_trgm
  gitlab:
    image: sameersbn/gitlab:10.3.3
    container_name: gitlab/gitlab-ce
    ports:
      - "10080:10080"
    hostname: "hxf.gitlab.top"
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://hxf.gitlab.top:10080'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
    depends_on:
      - redis
      - postgresql
    volumes:
      - /application/services/gitlab/config:/etc/gitlab
      - /application/services/gitlab/data:/var/opt/gitlab
      - /application/services/gitlab/logs:/var/log/gitlab